---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
env:
  - AR_VERSION="~> 5.2"
  - AR_VERSION="~> 4.2" SQLITE_VERSION="~> 1.3.9" MYSQL_VERSION="~> 0.4.0"
services:
  - mysql
  - postgresql
before_script:
  - mysql -u root -e 'CREATE DATABASE database_consistency_test;'
  - psql -U postgres -c 'CREATE DATABASE database_consistency_test;'
script:
  - bundle exec rspec
  - bundle exec rubocop

